### PR TITLE
Load timer services; just don't start them

### PR DESCRIPTION
**Pull request by thepwagner**
- prefer os.path.splitext() to .endswith()+.replace()
- spam loading process with debug code

### CODE REVIEW

**Comment by DeviaVir** [comment]
I was thinking loading units would start them for some reason and was looking in the _completely_ wrong place! 💯 

running a test deploy for this branch after which I'll 👍 or 👎

**Comment by DeviaVir** [comment]
:+1:

**Comment by thepwagner** [comment]
Will let dockerhub republish (I'd `docker push pebbletech/spacel-agent:load-timers`-ed for fast test cycles)

**Comment by DeviaVir** [comment]
doing a final test then merging in

**Comment by DeviaVir** [comment]
test seemed to have failed, but might be due to a different reason; it is listed in `systemctl list-timers` however so I'm going to go ahead and merge this in

**Pull request merged**
